Repository Maddoxx88/microregex, pull requests merged in 2022-10, with the labels that each got.

#6 Initial commit for Chakra UI, added react router and home page
  .prettierrc
  package.json
  src/App.css
  src/App.tsx
  src/components/navbar.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/pages/home.tsx
  src/theme.ts
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added Nhost Client to project.
  .env.example
  .gitignore
  src/App.tsx
  yarn.lock
Labels: hacktoberfest, hacktoberfest-accepted

#8 Add search and filters UI
  .env
  .prettierrc
  package.json
  src/App.tsx
  src/components/navbar.tsx
  src/pages/home.tsx
  src/theme.ts
  yarn.lock
Labels: hacktoberfest

#9 Added 3XN Grid
  src/components/card.tsx
  src/index.css
  src/index.tsx
  src/pages/home.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#10 Added card layout and click to copy action
  src/components/card.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#12 feat: add nhost graphql client
  package.json
  src/graphql/queries.ts
  src/pages/home.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#17 Changed boilerplate metadata
  public/index.html
  public/manifest.json
  src/components/navbar.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#19 Added inter variable font, fixed card UX
  package.json
  src/App.tsx
  src/components/card.tsx
  src/theme.ts
Labels: hacktoberfest, hacktoberfest-accepted

#20 Padding for search and filters
  src/pages/home.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#24 feat: display patterns, copy content
  .gitignore
  src/components/card.tsx
  src/graphql/queries.ts
  src/pages/home.tsx
  src/utils/copytext.ts
  src/utils/tags.ts
Labels: hacktoberfest, hacktoberfest-accepted

#25 22 implement language toggle besides search box
  src/App.tsx
  src/components/card.tsx
  src/pages/home.tsx
  src/utils/copytext.ts
Labels: hacktoberfest, hacktoberfest-accepted

#27 added search using name and tags
  src/components/card.tsx
  src/graphql/queries.ts
  src/pages/home.tsx
Labels: hacktoberfest, hacktoberfest-accepted

#34 added a new favicon and logo for landing page
  public/favicon.ico
  public/web-hero-logo.svg
  src/components/navbar.tsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#33 changed colors, font weights and sizes
  package.json
  src/App.tsx
  src/components/card.tsx
  src/pages/home.tsx
Labels: enhancement

#35 added preview text for card, changed queries for same
  src/components/card.tsx
  src/graphql/queries.ts
  src/pages/home.tsx
Labels: enhancement
